# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jimi Smoot
tagline: Software engineer who loves business
email: jsfour {at} gmail {dot} com
description: > # this means to ignore newlines until "baseurl:"
  Founder @meetvesper. Founded + sold 2 companies. Striving to build computers that help people make better decision.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jsfour.com" # the base hostname & protocol for your site
twitterUrl: "http://www.twitter.com/jsfour"
githubUrl:  "http://www.github.com/jsmootiv"
mediumUrl: "http://www.medium.com/@jsfour"
permalink: pretty

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

exclude:
  - CNAME
  - .gitignore
  - docker-compose.*
  - Dockerfile
  - Gemfile
  - Gemfile.lock
