# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jimi Smoot
tagline: Entrepreneur in training
email: jimi {at} jsfour {dot} com
description: > # this means to ignore newlines until "baseurl:"
  Entrepreneur in training
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.jsfour.com" # the base hostname & protocol for your site
# twitterUrl: "http://www.twitter.com/jsfour"
# githubUrl:  "http://www.github.com/jsmootiv"
# mediumUrl: "http://www.medium.com/@jsfour"
twitter:
  username: jsfour
  url: "https://www.twitter.com/jsfour"
medium:
  url: "https://www.medium.com/@jsfour"
github:
  url: "https://www.github.com/jsmootiv"
linkedin:
  url: "https://www.linkedin.com/in/jsfour"
permalink: /:title/
feed:
  path: atom.xml


# defaults:
#   - scope:
#       path: ""
#     values:
#       image: /assets/defaults/1024-512-default.png


# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  # TODO: set it up so that the first image of the post is used by the SEO tag plugin. This doesnt seem to work
  # - jekyll-auto-image

exclude:
  - CNAME
  - .gitignore
  - docker-compose.*
  - Dockerfile
  - Gemfile
  - Gemfile.lock
